install.packages("plotly", repos = 'http://cran.us.r-project.org')
install.packages("tidyverse", repos = 'http://cran.us.r-project.org')
install.packages("rgeos", repos = 'http://cran.us.r-project.org')
install.packages("shiny", repos = 'http://cran.us.r-project.org')
install.packages("devtools", repos = 'http://cran.us.r-project.org')
install.packages("leaflet", repos = 'http://cran.us.r-project.org')
install.packages("rgdal", repos = 'http://cran.us.r-project.org')
install.packages("raster", repos = 'http://cran.us.r-project.org')
install.packages("styler", repos = 'http://cran.us.r-project.org')
install.packages("spocc", repos = 'http://cran.us.r-project.org', dependencies = TRUE)
install.packages("sf", repos = 'http://cran.us.r-project.org')
install.packages("vegan", repos = 'http://cran.us.r-project.org')
install.packages("maps", repos = 'http://cran.us.r-project.org')
install.packages("tmap", repos = 'http://cran.us.r-project.org')
devtools::install_github("marlonecobos/ellipsenm", dependencies = T)
devtools::install_github('luismurao/ntbox', dependencies = T)
devtools::install_github("marlonecobos/kuenm", dependencies = T)
devtools::install_github("ipeaGIT/geobr", subdir = "r-package", dependencies = T)
devtools::install_github("ecohealthalliance/fasterize", dependencies = T)